"""donations table

Revision ID: 0d46a07c84a7
Revises: c15665284b0c
Create Date: 2020-11-06 15:42:29.871864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d46a07c84a7'
down_revision = 'c15665284b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_bank_id', sa.Integer(), nullable=False),
    sa.Column('volume_donated', sa.Integer(), nullable=False),
    sa.Column('date_of_donation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    # ### end Alembic commands ###
