"""removed lat-long

Revision ID: 551a3874f914
Revises: 3de2e4b91312
Create Date: 2020-11-05 12:38:54.156911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551a3874f914'
down_revision = '3de2e4b91312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blood_banks', 'latitude')
    op.drop_column('blood_banks', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_banks', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('blood_banks', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
