"""users donation

Revision ID: 78c31bd5738c
Revises: 0d46a07c84a7
Create Date: 2020-11-07 09:15:08.868777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c31bd5738c'
down_revision = '0d46a07c84a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_donation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_donation_date')
    # ### end Alembic commands ###
