"""notifications table

Revision ID: c889950c32f2
Revises: dbfe09b478b9
Create Date: 2020-11-07 16:37:07.558783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c889950c32f2'
down_revision = 'dbfe09b478b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User', sa.Integer(), nullable=False),
    sa.Column('BloodBank', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['BloodBank'], ['blood_banks.id'], ),
    sa.ForeignKeyConstraint(['User'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
