"""added city code

Revision ID: dbfe09b478b9
Revises: f133075ace17
Create Date: 2020-11-07 11:16:59.480475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfe09b478b9'
down_revision = 'f133075ace17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'city_code')
    # ### end Alembic commands ###
