"""state name unique

Revision ID: dd23a1dcb5d0
Revises: fba71669ec2d
Create Date: 2020-11-07 10:38:38.750786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd23a1dcb5d0'
down_revision = 'fba71669ec2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_name'), table_name='states')
    # ### end Alembic commands ###
